services:
  bot:
    build: .
    container_name: task_manager_bot
    depends_on:
      - mongodb
      - rabbitmq
    env_file:
      - .env
    volumes:
      - .:/app
    command: python bot/main.py
    restart: always
    networks:
      - my_network

  mongodb:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - my_network

  celery_worker:
    build: .
    container_name: celery_worker
    depends_on:
      - rabbitmq
      - mongodb
    env_file:
      - .env
    working_dir: /app/bot
    command: celery -A notification worker --loglevel=info --pool=solo
    restart: always
    networks:
      - my_network

  celery_beat:
    build: .
    container_name: celery_beat
    depends_on:
      - rabbitmq
      - mongodb
    env_file:
      - .env
    working_dir: /app/bot
    command: celery -A notification beat --loglevel=info
    restart: always
    networks:
      - my_network

volumes:
  mongo_data:

networks:
  my_network:
    driver: bridge